## 00. Pytorch Fundamentals

In [1]:
# Had trouble installing torch
# Remember to use !python -m pip install {package_name}
import torch
print(torch.__version__) # How do I get CUDA?

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.8.0+cpu


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created by using torch.tensor()

In [2]:
# scalar
scalar = torch.tensor(6)

In [3]:
scalar.item()

6

In [4]:
scalar.ndim

0

In [5]:
# Vector
vector = torch.tensor([6,6,])

In [6]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [7]:
# MATRIX
MATRIX = torch.tensor([[6, 7],
                       [8, 9]])

In [8]:
MATRIX.ndim

2

In [9]:
print(MATRIX[0])
print(MATRIX[1])

tensor([6, 7])
tensor([8, 9])


In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2],
                        [4, 3]],
                        [[12, 13],
                        [15, 16]],
                        [[111, 112],
                        [134, 124]],
                        [[1234, 4564],
                        [1243, 1343]]])

In [12]:
TENSOR

tensor([[[   1,    2],
         [   4,    3]],

        [[  12,   13],
         [  15,   16]],

        [[ 111,  112],
         [ 134,  124]],

        [[1234, 4564],
         [1243, 1343]]])

In [13]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9503, 0.7234, 0.8640, 0.2365],
        [0.4545, 0.3092, 0.4215, 0.7517],
        [0.4575, 0.1270, 0.5051, 0.2212]])

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
# Zeros and ones
zeros = torch.zeros(size=(3,4))

ones = torch.ones(size=(3, 4))

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [18]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

** Note: Tensor datatypes are one of the 3 big issues with pytorch and deeplearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [20]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               ### important parameters when using tensors
                               dtype=torch.float32, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # What device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [23]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [24]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors attributes

1. Tensors not right datatype - to get datatype from a tensor, you can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, you can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, you can use `tensor.device`

In [25]:
# Create a tensor
some_tensor = torch.rand((3, 4), dtype=torch.complex64)
some_tensor

tensor([[0.1626+0.4683j, 0.4827+0.6378j, 0.4390+0.5737j, 0.4123+0.4627j],
        [0.6377+0.2276j, 0.9166+0.9262j, 0.5738+0.3731j, 0.6853+0.2329j],
        [0.6346+0.8828j, 0.0234+0.6105j, 0.8481+0.7851j, 0.3576+0.0674j]])

In [26]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1626+0.4683j, 0.4827+0.6378j, 0.4390+0.5737j, 0.4123+0.4627j],
        [0.6377+0.2276j, 0.9166+0.9262j, 0.5738+0.3731j, 0.6853+0.2329j],
        [0.6346+0.8828j, 0.0234+0.6105j, 0.8481+0.7851j, 0.3576+0.0674j]])
Datatype of tensor: torch.complex64
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [33]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication

In [37]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]

value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [44]:
%%time

torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

# One of the most common errors in deep learning: shape errors

In [46]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix a tensor shape issue, we can manipulate the shape of our tensors using **transpose**

A **transpose** switches axes or dimensions of a given tensor

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [53]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [57]:
print(f"Original shapes: tensor_A = {tensor_A}, tensor_B = {tensor_B}")
print(f"New shapes: tensor = {tensor_A.shape}(same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dimensions must match")
print(f"Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
New shapes: tensor = torch.Size([3, 2])(same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding min, max, mean, sum, ect (tensor aggregation)

In [59]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
# Note: The torch.mean() function requires a float dtype in order to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [69]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [70]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finds the position in the tensor that has the minimum value with argmin()
# returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Finds the position in the tensor that has the maximum value with argmin()
# returns index position of target tensor where maximum value occurs
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a ceratin shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [85]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [88]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [89]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [90]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [92]:
# Stack tensors on each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [95]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [99]:
# torch.unsqueeze() - adds a single dimensions from a target tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension with  unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

# Permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1) # shifts the axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [110]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [111]:
# Index our new tensor
x[0, 0]

tensor([1, 2, 3])

In [114]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [119]:
# Let's index the most inner bracket
x[0][0][0]

tensor(1)

In [120]:
# You can also use a ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [122]:
# Get all values of the 0th dimension and 1st dimension but only take the index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [124]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [125]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [126]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

### PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(dnarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [129]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # pytorch turns the float64 into torch.float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [128]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Change the value of array, what will this do to  `tensor`?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [132]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [133]:
# Change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short, how a neural netowrk learns:

`start with random numbers -> tensor operations -> update random numbers to try and make the better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [135]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8000, 0.8062, 0.8962, 0.4431],
        [0.1539, 0.1624, 0.7906, 0.7525],
        [0.7626, 0.0811, 0.8375, 0.3521]])
tensor([[0.0214, 0.4754, 0.4505, 0.6204],
        [0.8185, 0.7740, 0.8618, 0.5358],
        [0.6165, 0.8704, 0.4571, 0.3241]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [151]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
#torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.4946, 0.9831, 0.5134, 0.2580],
        [0.5002, 0.6152, 0.6283, 0.6972],
        [0.5420, 0.5651, 0.0891, 0.8486]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Running tensors and PyTorch objects on the GPYs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scences to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use our own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acces them

For 2, 3 PyTorch + GPU drives (CUDE) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [152]:
!nvidia-smi

Wed Oct  8 12:09:42 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.54       Driver Version: 516.54       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [153]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. run on GPU if available, else default to CPU

In [155]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [156]:
# Count number of devices
torch.cuda.device_count()

0