## 00. Pytorch Fundamentals

In [2]:
# Had trouble installing torch
# Remember to use !python -m pip install {package_name}
import torch
print(torch.__version__) # How do I get CUDA?

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.8.0+cpu


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created by using torch.tensor()

In [3]:
# scalar
scalar = torch.tensor(6)

In [4]:
scalar.item()

6

In [5]:
scalar.ndim

0

In [6]:
# Vector
vector = torch.tensor([6,6,])

In [7]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [8]:
# MATRIX
MATRIX = torch.tensor([[6, 7],
                       [8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
print(MATRIX[0])
print(MATRIX[1])

tensor([6, 7])
tensor([8, 9])


In [11]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
TENSOR = torch.tensor([[[1, 2],
                        [4, 3]],
                        [[12, 13],
                        [15, 16]],
                        [[111, 112],
                        [134, 124]],
                        [[1234, 4564],
                        [1243, 1343]]])

In [33]:
TENSOR

tensor([[[   1,    2],
         [   4,    3]],

        [[  12,   13],
         [  15,   16]],

        [[ 111,  112],
         [ 134,  124]],

        [[1234, 4564],
         [1243, 1343]]])

In [34]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [44]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5444, 0.3924, 0.1650, 0.8023],
        [0.4838, 0.6010, 0.6906, 0.1508],
        [0.4556, 0.1050, 0.3645, 0.6032]])

In [45]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [49]:
# Zeros and ones
zeros = torch.zeros(size=(3,4))

ones = torch.ones(size=(3, 4))

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [50]:
ones.dtype

torch.float32