In [5]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt

!pip install torch
!pip install torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   -------------------------------- ------- 1.3/1.6 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 8.8 MB/s  0:00:00
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   --------------------------------- ------ 2.1/2.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 10.0 MB/s  0:00:00

   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ------------------------------

In [1]:
import matplotlib.pyplot as plt


In [ ]:
# dir = 'C:/Users/justi/Downloads/auto_price.csv'
# auto_price = pd.read_csv(dir)

In [6]:
# target_hp = auto_price[['target', 'horsepower']]
# target_hp

In [4]:
import torch

x = torch.randn(1, 3, 1, 4)
print(f"Original shape: {x.shape}") 

y = torch.squeeze(x)
print(f"Shape after squeezing all dimensions of size 1: {y.shape}")

z = torch.squeeze(x, dim=0) # Squeeze the first dimension (index 0)
print(f"Shape after squeezing dim 0: {z.shape}") 

print(f"This is what x looks like: \n {x}")
print(f"This is what y looks like: \n {y}")
print(f"This is what z looks like: \n {z}")

Original shape: torch.Size([1, 3, 1, 4])
Shape after squeezing all dimensions of size 1: torch.Size([3, 4])
Shape after squeezing dim 0: torch.Size([3, 1, 4])
This is what x looks like: 
 tensor([[[[-1.1835,  0.8514, -1.9015,  0.1564]],

         [[-0.3750,  0.6016,  0.8139, -0.9016]],

         [[-0.4084, -0.2162, -0.0173,  1.8595]]]])
This is what y looks like: 
 tensor([[-1.1835,  0.8514, -1.9015,  0.1564],
        [-0.3750,  0.6016,  0.8139, -0.9016],
        [-0.4084, -0.2162, -0.0173,  1.8595]])
This is what z looks like: 
 tensor([[[-1.1835,  0.8514, -1.9015,  0.1564]],

        [[-0.3750,  0.6016,  0.8139, -0.9016]],

        [[-0.4084, -0.2162, -0.0173,  1.8595]]])
